MODEL:
  META_ARCHITECTURE: "THGCL"
  AUDIO_BACKBONE:
    NAME: "Vggish"
    PRETRAINED_ON: ""
  VIDEO_BACKBONE:
    NAME: "S3D"
    PRETRAINED_ON: ""
  IMAGE_BACKBONE:
    NAME: "Resnet"
    PRETRAINED_ON: "ImageNet"
  HIDDEN_CHANNELS: 512
  NUM_LAYERS: 4
TRAINING:
  LOSS: "Lfc"
GRAPH:
  DYNAMIC: False
  SPAN_OVER_TIME_AUDIO: 6
  AUDIO_DILATION: 3
  SPAN_OVER_TIME_VIDEO: 4
  VIDEO_DILATION: 4
  SPAN_OVER_TIME_BETWEEN: 3
  NORMALIZE: False
  SELF_LOOPS: True
  FUSION_LAYERS: []
DATASETS:
  TRAIN_RATIO: 0.7
  EVAL_RATIO: 0.1
  TEST_RATIO: 0.2
  TRAIN_PATH: 'E:/sedDatasets/audiosetfea/AudioSet_embedds_all.h5'
  TEST_PATH: ''
  EVAL_PATH: ''
TEST:
  MAX_PATIENCE: 5
  EVAL_PERIOD: 250
DATALOADER:
  BATCH_SIZE: 64
  STRATIFIED_SPLIT: True
SOLVER:
  BASE_LR: 0.005
  STEPS: (250,)
  MAX_ITER: 5000
  WARMUP_ITERS: 1000
INPUT:
  MIN_SIZE_TRAIN: (500, 600, 700, 800, 900, 1000)
VERSION: 0
SEED: 1024
